{"name": "Логин с неверным логином", "status": "passed", "start": 1730016751687, "stop": 1730016752009, "uuid": "37da903f-6097-48d6-86e1-8a99d762d4a1", "historyId": "3af58d3500609849f527f5fe56ca4aec", "testCaseId": "3af58d3500609849f527f5fe56ca4aec", "fullName": "tests.test_login_user.TestLoginUser#test_invalid_login_user", "labels": [{"name": "suite", "value": "Логин пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-COFSJ1F"}, {"name": "thread", "value": "29476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}